### ISSUE TITLE
Replace `game-scanner` library with simple call to Windows registry

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#101]
With #99 we use [`game-scanner`](https://crates.io/crates/game-scanner) as a library to get Origin Titanfall2 install on Windows. However this library adds quite a bunch of dependencies increasing build time.

@mrsteyk suggested using [`winreg`](https://crates.io/crates/winreg) to query Windows registry directly instead.

**Comment by GeckoEidechse** [comment]
Given that current release (`1.1.4`) of `game-scanner` does not compile with Rust 1.69, this is issue is now high priority. Currently compilation issue is fixed by patching the library but given the lack of updates in the library I think it's high time to just replace it entirely...

**Comment by Jan200101** [comment]
In a fresh Windows VM running Origin with a fresh Install of non-steam Titanfall2 these are the keys the note the install location (ignoring duplicates and generated uninstall and firewall entries):

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Respawn\Titanfall2]
"Install Dir"="C:\\Program Files (x86)\\Origin Games\\Titanfall2\\"

```

**Comment by Jan200101** [comment]
Interestingly, the same registry entry is used for the EA App.

So if this is queried it would support both.
