### ISSUE TITLE
Expose core mods from backend to frontend

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#120]
> Hmm, for that we need to signal core mods from backend to front-end. I don't think we have something for that yet... :/

_Originally posted by @GeckoEidechse in https://github.com/R2NorthstarTools/FlightCore/pull/110#discussion_r1054898148_

**Comment by Alystrasz** [comment]
Without a need for signals, this is more a problem of code sharing between frontend and backend.
I think we should explore automatically building Typescript types, using a tool like https://github.com/Aleph-Alpha/ts-rs

**Comment by GeckoEidechse** [comment]
> I think we should explore automatically building Typescript types, using a tool like https://github.com/Aleph-Alpha/ts-rs

Once #140 is merged which uses `ts-rs`, we could create a global const vector and expose that via `ts-rs` I think. Alternatively if that doesn't work the fall back would be to have a function call that returns the list of core mods.

**Comment by GeckoEidechse** [comment]
Turns out you cannot use `ts-rs` for global consts. It's only for structs (which makes sense I guess). I think it'll make most sense to a have a call into backend that fetches the list of consts where necessary.

**Comment by GeckoEidechse** [comment]
Actually, the only place where we declare some const a second time is in https://github.com/R2NorthstarTools/FlightCore/blob/a7e28562bb64e800f30b4f82a942ece2284b4121/src-vue/src/plugins/store.ts#L249 which is planned to be replaced with a call to backend anyway... ^^
