### ISSUE TITLE
Middle mouse button not working when launching through FligthCore

### ISSUE THREAD

**Issue by laundmo** [R2NorthstarTools/FlightCore#137]
works with:

- r2modman
- manual launch

with flightcore it just doesn't detect the button is clicked

**Comment by GeckoEidechse** [comment]
Cannot reproduce on my end. I have tactical bound to middle mouse and it just works fine when testing right now on a listen server.

Do you have multiple versions of the game installed (Steam and Origin)? Cause FlightCore might launching a different version then you are used to and as such loading different keybinds from config file in documents folder.

You can check the Titanfall2 install that FlightCore found in the settings tab.

Also note that all FlightCore does when launching the game is `cd`ing into the Titanfall2 folder it found and running `start "" "NorthstarLauncher.exe"`.

**Comment by laundmo** [comment]
> Do you have multiple versions of the game installed (Steam and Origin)? Cause FlightCore might launching a different version then you are used to and as such loading different keybinds from config file in documents folder.

nope

> You can check the Titanfall2 install that FlightCore found in the settings tab.

it shows the correct path, in fact i copied this path when manually launching


guess its all irrelevant as i just tried again and it works fine. i tried it back and forth 3 times before and it was always broken on flight core. well, thats confusing.
