### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#172]
- [ ] Figure out how to do translations
- [ ] Add weblate integration
- [ ] Add them

**Comment by Alystrasz** [comment]
Does weblate enforce using a particular template?
I suggest using [vue-i18n](https://vue-i18n.intlify.dev/guide/) otherwise.

**Comment by GeckoEidechse** [comment]
> Does weblate enforce using a particular template?

I think you can adapt it to basically any format using custom rules. @p0358 to confirm

> I suggest using [vue-i18n](https://vue-i18n.intlify.dev/guide/) otherwise.

Sounds like a plan ^^

**Comment by p0358** [comment]
Yeah we use simple "JSON file" format in Weblate for TFORevive Launcher, and we also use vue-i18n for translations.
