### ISSUE TITLE
Button to fix issues introduced by auto-matchmaker mod

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#183]
Once RepairView is released.

1. Remove AMM mod
2. Remove `ns_has_agreed_to_send_token 2` from `ns_startup_args.txt` (or replace with 1)

https://discord.com/channels/920776187884732556/942391932137668618/1075835558078709840 (discussion about this in private channel on Northstar Discord server)

**Comment by Alystrasz** [comment]
Could you be a bit more specific? :smile:

**Comment by GeckoEidechse** [comment]
Not sure if this is actually still needed with vanilla match-making being fixed and the auto-matchmaking mod being removed from Thunderstore.

Closing as WONTFIX for now ^^
