### ISSUE TITLE
Launch Northstar "detached"

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#20]
Right now Northstar is launched as a child which means it captures all the child's stdout which breaks stuff such as @ASpoonPlaysGames's colour console logs PR.

**Comment by GeckoEidechse** [comment]
Possible useful link for later: https://doc.rust-lang.org/std/process/struct.Stdio.html#method.piped

**Comment by Alystrasz** [comment]
Closed by #112.
