### ISSUE TITLE
Installation folder does not save

### ISSUE THREAD

**Issue by Happylama25** [R2NorthstarTools/FlightCore#213]
Every time I open the launcher, it states "Titanfall2 not found!" even after setting the installation location.

Setting the location, and checking in the launcher settings, show the correct directory.
![image](https://user-images.githubusercontent.com/49815691/225722841-eeb710f4-9c7e-4aac-be46-379a35cd057c.png)

But upon closing and reopening the launcher, it doesn't save.
![image](https://user-images.githubusercontent.com/49815691/225723030-91669f15-64d6-4670-884e-0266251046d7.png)
![image](https://user-images.githubusercontent.com/49815691/225723036-68cbe95b-87bc-4786-a614-c80ac1c6339b.png)

FlightCore Version: v1.10.1

**Comment by Alystrasz** [comment]
Can you send a screenshot of your `E:\Origin\Titanfall2` directory content?

**Comment by GeckoEidechse** [comment]
Oh the `&` in the file name might causing it? Will need to do some testing first to confirm ^^

If that's the case I'll try to find a fix

**Comment by Happylama25** [comment]
It's a windows box, and file directories ignore the name of the drive I think, just the assigned letter, I don't think it's because of the name, not sure what it could be, works with VTOL launcher and Viper launcher just fine.

**Comment by Happylama25** [comment]
Well, that's weird, it works perfectly now, after 2 days (with 2 restarts) it now saves the location just fine. I changed absolutely nothing.
