### ISSUE TITLE
Add license.

### ISSUE THREAD

**Issue by begin-theadventure** [R2NorthstarTools/FlightCore#234]
FlightCore uses code from Papa, so MIT license.

**Comment by GeckoEidechse** [comment]
Oh lol forgot to ever add one whoops...
Given that the rest of Northstar uses MIT I guess we should we go with that as well. Unless we wanna go for GPL3 instead?

@Alystrasz thoughts? ^^

**Comment by Alystrasz** [comment]
The only difference between both licences is that GPL3 forces all modifications to be open-sourced, right?
I'm not sure FlightCore would get any benefit from this particular rule.

**Comment by GeckoEidechse** [comment]
Yeah, GPL3 requires all changes that are redistributed to also be open sourced. I think MIT is fine for now ^^
