### ISSUE TITLE
Arch User Repository.

### ISSUE THREAD

**Issue by begin-theadventure** [R2NorthstarTools/FlightCore#235]
Hello, I made a -bin PKGBUILD for FlightCore, but I can't/dunno how to submit it to the AUR, would you like to do that or should I send it to someone else?

**Comment by GeckoEidechse** [comment]
I have never used/packaged for the AUR nor am I planning to. You're free to get someone to do it but please make sure to mark the package as "unofficial". I will not be fixing any issues related to the AUR specifically nor will I link to it in the README.
