### ISSUE TITLE
Instructions for building.

### ISSUE THREAD

**Issue by begin-theadventure** [R2NorthstarTools/FlightCore#238]
Would it be possible to add instructions for building from source code? ~~I tried, but failed (I can add more information if needed).~~ Never mind, I managed to build it by looking at the [workflow file](https://github.com/R2NorthstarTools/FlightCore/actions/runs/4462846117/workflow) although it also bundles deb and appimage.

**Comment by GeckoEidechse** [comment]
I assumed the [build instructions](https://github.com/R2NorthstarTools/FlightCore/blob/main/docs/DEVELOPMENT.md#setup), which are [linked in the main README](https://github.com/R2NorthstarTools/FlightCore#development) are enough but if not I'm happy to improve them on any point where you might see an issue with them. ^^

**Comment by begin-theadventure** [comment]
They can be helpful, although they won't build, unlike those in the workflow file.
I tried to build in src-tauri, but it does the same thing as in the main folder, bundles the AppImage and deb, so I would like to know how to build just the binary. Maybe I'd have to change some configuration to do that?
The commands I've used: `npm install && cd src-vue && npm install && cd ../src-tauri && npm run tauri build` (and `cargo-tauri build`, but it's the same, I guess).
I wonder if such arguments would be a good idea:
`npm run tauri build flight-core` - binary only; appimage/deb if binary exists.

**Comment by begin-theadventure** [comment]
They can be helpful, although they won't build, unlike those in the workflow file.
I tried to build in src-tauri, but it does the same thing as in the main folder, bundles the AppImage and deb, so I would like to know how to build just the binary. Maybe I'd have to change some configuration to do that?
The commands I've used: `npm install && cd src-vue && npm install && cd ../src-tauri && npm run tauri build` (and `cargo-tauri build`, but it's the same, I guess).

**Comment by GeckoEidechse** [comment]
What's the error message you're seeing?

Keep in mind that by default the auto-updater is enabled and it requires a private key to sign the finished build. You can disable the updater by setting the [corresponding value](https://github.com/R2NorthstarTools/FlightCore/blob/c102fdcf8ef00e3c5c46fb9ded37e09b7e92e483/src-tauri/tauri.conf.json#L54) to `false` in `tauri.conf.json`.

As for building "just the binary", you'll have to take that issue upstream. Tauri build scripts for Linux only produce an AppImage and `.deb` package (in the future also Flatpak as far as I can tell).

**Comment by begin-theadventure** [comment]
Oh, it would be great if there were something like npm run tauri build -binary / -appimage / -deb.
> You can disable the updater by setting the [corresponding value](https://github.com/R2NorthstarTools/FlightCore/blob/c102fdcf8ef00e3c5c46fb9ded37e09b7e92e483/src-tauri/tauri.conf.json#L54) to false in tauri.conf.json.

Cool, I didn't know that.
Thank you very much for your help!

**Comment by begin-theadventure** [comment]
I finally found on the AUR how to do it :)
tauri.conf.json
```
    "bundle": {
      "active": true,
```
to false
``npm install && cd src-vue && npm install && cd ../src-tauri && npm run tauri build``
Perhaps I could write a section about building or edit the setup section?

**Comment by begin-theadventure** [comment]
I finally found on the AUR how to do it :)
tauri.conf.json
```
    "bundle": {
      "active": true,
```
to false
``npm install && cd src-vue && npm install && cd ../src-tauri && npm run tauri build``
Perhaps I could write a section about building or edit the setup section? Unless you want to do it yourself.

**Comment by GeckoEidechse** [comment]
Feel free to do so <3
