### ISSUE TITLE
Visual bug with router refactor

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#26]
Seems to work fine in testing for the most part. `mounted()` no only gets called when the view is actually opened, i.e. what we wanted to achieve with this PR ^^

One issue I noticed is that when enabling/disabling dev mode, the highlighted tab at the top gets updated incorrectly.
In particular, enabling dev mode highlights the _DEV_ tab even though it isn't the open one:
![screenshot](https://user-images.githubusercontent.com/40122905/196916949-b2fa4f67-39a4-4ce4-9cd2-8d0d232b470b.png)

and disabling dev mode switches back to _PLAY_ view but doesn't highlight it:
![screenshot](https://user-images.githubusercontent.com/40122905/196917576-809053d9-5f62-4e21-bee2-6ec6471249f7.png)

_Originally posted by @GeckoEidechse in https://github.com/GeckoEidechse/FlightCore/pull/25#pullrequestreview-1148934672_

**Comment by Alystrasz** [comment]
When the dev mode is toggled off, we call `router.push({path: Tabs.PLAY});` which correctly updates view, but not the menu, and I have no clue why.

Possible resource: https://gist.github.com/languanghao/5f74ca361f22192ba774941a69fd275b
