### ISSUE TITLE
FlightCore only showing white on debug build

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#268]
This is a really weird bug that only affects one of my own Windows machines. Basically browser console says there's some syntax error:

![image](https://user-images.githubusercontent.com/40122905/232331585-546e1e52-42b5-48d5-9200-5391929ad211.png)

My Linux machine doesn't have that issue. Similarly release builds still work fine. And for debug builds checking the localhost address in browser is also fine. It's only just the WebView2 window on FlightCore debug build that has that issue.

Reloading window does nothing. I already tried cleaning and reinstalling npm packages more times than I have fingers... Reinstalling WebView2 also didn't fix it x_x

**Comment by Alystrasz** [comment]
Did you install frontend dependencies on your Windows machine? (`npm i` in `src-vue` directory)

**Comment by GeckoEidechse** [comment]
Yup, all npm dependencies installed for both project root and `src-vue`...

Double checked now and still the same x_x

**Comment by Alystrasz** [comment]
What exactly is the "invalid or unexpected token"?
You can show it by clicking the `@element_plus_icons-vue.js` link.

**Comment by GeckoEidechse** [comment]
Don't have access to that PC rn unfortunately, will have to recheck when I got access to it again ^^

**Comment by GeckoEidechse** [comment]
> What exactly is the "invalid or unexpected token"? You can show it by clicking the `@element_plus_icons-vue.js` link.

Nothing apparently cause the source root dir isn't set...

**Comment by GeckoEidechse** [comment]
I ultimately "resolved" the issue by just doing a fresh clone of the repo to a different location. Still no idea what caused but at least it works again for now ¯\\\_(ツ)\_/¯

**Comment by GeckoEidechse** [comment]
Happening again x_x

**Comment by GeckoEidechse** [comment]
This makes no sense

![image](https://github.com/R2NorthstarTools/FlightCore/assets/40122905/fc52c56d-e214-4bc5-9de6-0739e82d823b)

**Comment by GeckoEidechse** [comment]
It's doing a request to Thunderstore?!

![image](https://github.com/R2NorthstarTools/FlightCore/assets/40122905/be6be40e-a4cb-4339-9924-931e526a4dd0)

**Comment by GeckoEidechse** [comment]
Force reload (`CTRL` + `SHIFT` + `R`) fixed it, wtf? XD

**Comment by username-generic** [comment]
I'm getting the same blinding white window on Fedora Linux, this is the console output of the latest AppImage version:
```
WARN  arboard::platform::linux > Tried to initialize the wayland data control protocol clipboard, but failed. Falling back to the X11 clipboard protocol. The error was: Unknown error while interacting with the clipboard: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor

** (flight-core:59033): WARNING **: 22:38:08.924: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

** (flight-core:59033): WARNING **: 22:38:33.941: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by GeckoEidechse** [comment]
Not sure if it's the same issue but yes, Linux AppImage builds are broken atm and I have no idea why. Can you make a new issue for this? Then I can pin it ^^

**Comment by username-generic** [comment]
Done #1079

**Comment by GeckoEidechse** [comment]
Thanks. Pinned it 👍
