### ISSUE TITLE
Sort Thunderstore mod browser by outdated first

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#293]
Right now there's not an easy way in FlightCore to see which mods are outdated. The optimal way would be to update the local mods view to show outdated Thunderstore mods.

Until this is done (I'm rather busy atm) we could also update the sort function in the Thunderstore mod browser view to sort by outdated first and then by upload date.

This way opening Thunderstore mod browser would instantly show all outdated mods ^^

**Comment by GeckoEidechse** [comment]
@Alystrasz thoughts? ^^

**Comment by Alystrasz** [comment]
I don't think we should show Thunderstore mods in local mods view.
More than putting outdated mods first, we could also display [a badge](https://element-plus.org/en-US/component/badge.html) on the "Online mods" menu item, showing how many mods are outdated.

**Comment by GeckoEidechse** [comment]
> I don't think we should show Thunderstore mods in local mods view.

I meant as in have a way in local mods to see which (Thunderstore) mods are outdated ^^

> More than putting outdated mods first, we could also display [a badge](https://element-plus.org/en-US/component/badge.html) on the "Online mods" menu item, showing how many mods are outdated.

A badge has been on my todo list for a while. From the badge the user needs a way to see the outdated mods though. Kinda annoying otherwise if it tells you how many mods are outdated but no easy way to update them ;)

**Comment by GeckoEidechse** [comment]
Actually we could also do `Installed` as a sort option to quickly see which Thunderstore mods are installed. In general in FlightCore it's currently super difficult to see which Thunderstore mods are installed.
