### ISSUE TITLE
Can't search for PRs with spaces

### ISSUE THREAD

**Issue by uniboi** [R2NorthstarTools/FlightCore#296]
In the dev testing area you can't filter PRs with spaces because space toggles the accordeon

![image](https://user-images.githubusercontent.com/64006268/235343828-773d5f9c-6c77-4e91-b959-e6a6c1da698f.png)

**Comment by GeckoEidechse** [comment]
Can confirm, and it's kinda funny xD
No idea how to fix other than moving filter outside accordion. @Alystrasz any ideas? ^^"


In the meantime, copy/pasting a space character works as a stupid workaround...

**Comment by Alystrasz** [comment]
Yeah, I was actually aware of this behavior, I wondered how long it would go unnoticed x)
