### ISSUE TITLE
PR testing tool doesn't fetch all available PRs

### ISSUE THREAD

**Issue by uniboi** [R2NorthstarTools/FlightCore#297]
Doesn't fit on a screenshot but the oldest mods PR I can install is R2Northstar/NorthstarMods#536. I have no issues for R2Northstar/NorthstarLauncher, maybe because there aren't enough open PRs

**Comment by GeckoEidechse** [comment]
> I have no issues for R2Northstar/NorthstarLauncher, maybe because there aren't enough open PRs

Exactly this. The reason is cut off is cause API results are paginated and I only fetch the first page. Pretty sure I fixed this somewhere else before so this shouldn't be difficult to fix. Just glad someone finally noticed it ;P

**Comment by GeckoEidechse** [comment]
Pushed a fix to #298 which is awaiting merge. Feel free to download CI artifact and check if it works for you. If it does, LMK and I can merge early and release ^^
