### ISSUE TITLE
Show when mod is marked deprecated in Thunderstore mod browser

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#307]
Currently we don't show when a mod is deprecated in Thunderstore mod browser

![image](https://user-images.githubusercontent.com/40122905/236619805-afb9e4a8-d65a-4a34-a7bc-b08dc39660d8.png)

**Comment by Alystrasz** [comment]
I'm pretty sure uniboi already reported this at some point and I addressed it, but I can't find related messages 🤡
