### ISSUE TITLE
Add a notifications button

### ISSUE THREAD

**Issue by F1F7Y** [R2NorthstarTools/FlightCore#400]
When installing mod PRs, etc i quite often alt+tab to read the PR descriptions and miss the notification that the PR has been successfully installed. While im sure your code is robust and wouldn't fail, it would be a nice QOL feature to be able to check previous notifications.

Something, something like this:
![image](https://github.com/R2NorthstarTools/FlightCore/assets/64418963/9fdb1b3e-fd3f-4c47-b825-6fe41bc309c2)

**Comment by GeckoEidechse** [comment]
@Alystrasz the notification class in [element plus](https://element-plus.org/) doesn't store any information in this regard, right? So we would have to add that to our wrapper ig?

Alternatively if that's just for PR I can also set the notification to not disappear.

**Comment by GeckoEidechse** [comment]
Actually, we could probably grab status if window is focused and only time out notifications when window is actually focused.

**Comment by Alystrasz** [comment]
> @Alystrasz the notification class in [element plus](https://element-plus.org/) doesn't store any information in this regard, right? So we would have to add that to our wrapper ig?

Nah, we must handle this ourselves.

Another solution is to use system notifications: https://tauri.app/fr/v1/api/js/notification/

**Comment by GeckoEidechse** [comment]
> Another solution is to use system notifications: https://tauri.app/fr/v1/api/js/notification/

Hmm, that could also work. Then we just let the OS handle the rest. Although I would limit that to only when window is out of focus as getting a system notification for everything will probably become annoying ^^
