### ISSUE TITLE
Not yet implemented for "linux" with Titanfall2 installed via "UNKNOWN"

### ISSUE THREAD

**Issue by g1sbi** [R2NorthstarTools/FlightCore#411]
I installed northstar using the AppImage. after selecting my game folder and installing it, when trying to launch I get 
`Not yet implemented for "linux" with Titanfall2 installed via "UNKNOWN"`

this pops up in the terminal:
```
[src/northstar/mod.rs:63] game_install.clone() = GameInstall {
    game_path: "/home/gisbi/storage/steamlibrary/steamapps/common/Titanfall2",
    install_type: UNKNOWN,
    ````

**Comment by GeckoEidechse** [comment]
Ah it didn't pick up the steam install path cause it's not a default path I guess. Launching on Linux is very much still WIP. So for now I'd suggest to just follow [the Northstar wiki on how to install the right Proton version and launch the game](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/steamdeck-and-linux/installing-on-steamdeck-and-linux).

Proper Linux support is being worked on. In the meantime you should very much still be able to use FlightCore to install mods and updates, and just launch Northstar outside of FlightCore using the wiki instructions. ^^

**Comment by g1sbi** [comment]
Following the [wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/steamdeck-and-linux/installing-on-steamdeck-and-linux), I tried using NorthstarProton and launching directly from Steam using the launch options. This fixed the issue.
