### ISSUE TITLE
Blank main window

### ISSUE THREAD

**Issue by theunkn0wn1** [R2NorthstarTools/FlightCore#571]
When attempting to run FlightCore 2.9.3 via its appimage or manually compiled release binary on Ubuntu, The main window starts but renders nothing.
I even went as so far as to compile the application from source in an attempt to resolve the issue, alas the problem persists.

![image](https://github.com/R2NorthstarTools/FlightCore/assets/3110986/d25b389a-8e88-464d-a188-642d0fb8cd17)

```
$ src-tauri/target/release/flight-core 
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
 INFO  app::github::release_notes > Checking GitHub API
 INFO  app::github::release_notes > Fetching releases notes from GitHub API
 INFO  app                        > Titanfall2.exe exists in path? true
 INFO  app::northstar             > /mnt/86905182-2968-4fc9-8e44-207e0a1e5b08/steam/steamapps/common/Titanfall2
 INFO  app::github::release_notes > Done checking GitHub API
 INFO  app::util                  > total_player_count: 183
 INFO  app::util                  > server_count:       166
^C

~/Downloads/titanfall/FlightCore on  main ⌚ 20:56:19
$ git rev-parse HEAD
4d61ffe0439dd1e145ec5ea992ea48978034bd78

```

Host information:
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 5.15.0-83-generic 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile

**Comment by theunkn0wn1** [comment]
Caused by upstream bug: https://github.com/tauri-apps/tauri/issues/5143#issuecomment-1311815517

setting `WEBKIT_DISABLE_COMPOSITING_MODE=1` allows the main window to render.

![image](https://github.com/R2NorthstarTools/FlightCore/assets/3110986/ee9719c6-5d72-4935-b37e-58a61298b972)

**Comment by GeckoEidechse** [comment]
Oh wow, good catch. Thanks for the detailed report and corresponding PR <3
