### ISSUE TITLE
Titanfall2 install check for Origin opens powershell window

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#58]
To get Origin install location on Windows we parse registry. For this we use a PowerShell command. Apparently this opens powershell window for short second which is an issue as it unsettles players.

https://github.com/GeckoEidechse/FlightCore/blob/bbcfb260b3717c943244d889c5d8d819efa576f9/src-tauri/src/lib.rs#L96-L109

**Comment by Alystrasz** [comment]
@GeckoEidechse I supposed this is fixed with #112?

**Comment by GeckoEidechse** [comment]
Actually #99 but regardless it's resolved now ^^
