### ISSUE TITLE
Delay GitHub update warning until X hours after release

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#80]
CI currently takes 20 minutes to build. This means that when making a release, there's a 20 minute window where FlightCore will show a warning notification that it's outdated but not offer a way to update.

As such we should have a 1 hour (or some other duration) delay where we don't show the "FlightCore outdated" warning notification.

**Comment by Alystrasz** [comment]
With #98, update notification will show starting from 2 hours after release build.
