### ISSUE TITLE
FlightCore not picking up Steam install on Bazzite

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#887]
For some reason, FlightCore failed to pick up

```
/var/home/USERNAME/.local/share/Steam/steamapps/common/Titanfall2/ 
```
https://discord.com/channels/920776187884732556/942505193893945394/1227964817755738175

so the person in question had to manually set the path in FlightCore.

We should figure out why picking up Steam path does (apparently) not work on Bazzite
(Especially as we are featured as an app on [Bazzite's website](https://bazzite.gg/) lol)

**Comment by Jan200101** [comment]
looking into this

**Comment by Jan200101** [comment]
Tested in a fresh Bazzite VM and found no issues.

![image](https://github.com/R2NorthstarTools/FlightCore/assets/15076013/e0e0f4b0-87e8-41e2-a2e8-7b4ab8eee5b9)

**Comment by GeckoEidechse** [comment]
Closing as not reproducible then ig ^^

Thanks for testing <3
